[[constraint]]
  name = "fyne.io/fyne"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/BakeRolls/mri"

[[constraint]]
  name = "github.com/Girbons/mangarock"
  version = "1.2.1"

[[constraint]]
  name = "github.com/anaskhan96/soup"
  version = "1.1.1"

[[constraint]]
  name = "github.com/bmaupin/go-epub"
  version = "0.5.0"

[[constraint]]
  name = "github.com/jung-kurt/gofpdf"
  version = "2.4.0"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "3.1.1"

[[constraint]]
  name = "github.com/schollz/progressbar"
  version = "2.12.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
